project:
  type: website
  output-dir: docs

website:
  title: "Naim Montazeri, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Research Projects
      - href: publications.qmd
        text: Publications
      - href: presentations.qmd
        text: Presentations
      - href: outreach.qmd
        text: Outreach
      - href: certificates.qmd
        text: Certificates
      - href: expertise.qmd
        text: Expertise
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/naimont
      - icon: link-45deg
        href: https://zenodo.org/communities/food-environ-virol/
      - icon: linkedin
        href: https://www.linkedin.com/in/nmontazeri/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    include-after-body: footer.html

editor: visual