project:
  type: website
  output-dir: docs

website:
  title: "Naim Montazeri, Ph.D."
  google-analytics: "G-BXKKJYS4JG"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Research Projects
      - href: publications.qmd
        text: Publications
      - href: presentations.qmd
        text: Presentations
      - href: outreach.qmd
        text: Outreach
      - href: certificates.qmd
        text: Certificates & Awards
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/naimont

      - text: "<img src='https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/zenodo.svg' width='18' style='vertical-align: middle;'/>"
        href: https://zenodo.org/communities/microbial-food-safety/

      - icon: linkedin
        href: https://www.linkedin.com/in/nmontazeri/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    include-after-body: footer.html

editor: visual