---
title: "Selected Presentations (total +60)"
---

My invited talks focus on translating complex microbiological data into practical food safety insights for scientific, regulatory, and industry audiences.

-   *Vibrio* phages and food safety – *Phage Meeting, UF Emerging Pathogen Institute*. Gainesville, FL. November 14, 2025.

-   Assessment and mitigation of foodborne pathogens. Microbiology Research Panel. *ASM Gators - UF Students Chapter*. Gainesville, FL. February 24, 2025.

-   Inferential modeling of coronavirus persistence and surface-mediated transfer to human skin. *IAFP Annual Meeting*, Long Beach, CA. July 27–30, 2024.

-   Preharvest mitigation of norovirus in agricultural water using chemical sanitizers. IAFP Annual Meeting. Toronto, Canada. July 16-19, 2023.

-   Modeling coronavirus persistence and human exposure through surface-to-skin transfer. *FAFP — AEC*. St. Petersburg, FL, May 14-16, 2024.

-   Environmental persistence and antibacterial efficacy of bacteriophages against *Vibrio parahaemolyticus*. *FAFP — AEC*. Lake Buena Vista, FL. May 16-18, 2023.

-   Mitigation of norovirus contamination in water. *FAFP — AEC*. Lake Buena Vista, FL. May 18, 2022.

-   Biocontrol potentials of bacteriophages against *Vibrio parahaemolyticus*. *Florida Branch of ASM — Annual Meeting*. Orlando, FL. Oct 21-23, 2022.

-   *In vitro* testing of lytic bacteriophages isolated from virulent strains of *Vibrio parahaemolyticus* for biocontrol applications. *IAFP Annual Meeting*, Pittsburgh, PA. 2022.

-   Virus surrogates in persistence and inactivation studies. University of Georgia, Department of Food Science and Technology. Nov 18, 2021.

-   Environmental persistence and antibacterial efficacy of bacteriophages against *Vibrio parahaemolyticus*. *FAFP — AEC*. Lake Buena Vista, FL. May 16-18, 2023.
